apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
  pollingInterval: 3
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0 # No delay in scaling up
          policies:
            - type: Percent
              value: 100 # Can scale up by 100% of current pods
              periodSeconds: 3 # Every 3 seconds
        scaleDown:
          stabilizationWindowSeconds: 10 # Wait 10 seconds before scaling down
          policies:
            - type: Percent
              value: 100 # Can remove 100% of excess pods
              periodSeconds: 5
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/571653956102/keda-test
        queueLength: "3"
        activationQueueLength: "2"
        awsRegion: "us-east-1"
        identityOwner: "kubernetes"
