apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: default
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: dhairya13703/sqs-producer:v1 # Replace with your image
          env:
            - name: QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/571653956102/keda-test" # Replace with your queue URL
            - name: COUNT
              value: "100" # Increased message count
            - name: INTERVAL
              value: "10" # Reduced interval to 100ms
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
